"""Build generated themes: {style}.{industry} CSS from palette tokens.

Authoring happens HERE (offline). The online service stays deterministic:
it only reads the emitted CSS files and the registry in app/render.py.

Run:  python tools/build_themes.py
Writes app/templates/cards.<industry>/{cover,section}.css and FAILS if any
text/background pair drops below WCAG AA (4.5:1).
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "app" / "templates"

# Palette tokens per industry. Seeded from the ui-ux-pro-max design
# intelligence (domain=color queries) and adapted for slide contrast.
PALETTES: dict[str, dict[str, str]] = {
    # tech: navy ink + blue accent (skill: B2B professional navy)
    "tech": dict(
        bg="#f8fafc", ink="#0f172a", body="#334155", muted="#475569",
        accent="#0369a1", card="#ffffff", border="#e2e8f0", soft="#dbeafe",
        shadow="#dbeafe", chip_bg="#0f172a", chip_fg="#7dd3fc",
    ),
    # finance: navy + restrained gold (skill: finance/banking)
    "finance": dict(
        bg="#f8fafc", ink="#0f172a", body="#334155", muted="#475569",
        accent="#a16207", card="#ffffff", border="#e2e8f0", soft="#fef3c7",
        shadow="#e2e8f0", chip_bg="#0f172a", chip_fg="#fbbf24",
    ),
    # edu: teal + warm orange (skill: education platform)
    "edu": dict(
        bg="#f0fdfa", ink="#134e4a", body="#0f766e", muted="#115e59",
        accent="#b45309", card="#ffffff", border="#ccfbf1", soft="#ffedd5",
        shadow="#ccfbf1", chip_bg="#134e4a", chip_fg="#5eead4",
    ),
    # energy: industrial dark + safety orange (skill: manufacturing/energy)
    "energy": dict(
        bg="#1f2937", ink="#f8fafc", body="#e2e8f0", muted="#cbd5e1",
        accent="#f97316", card="#273549", border="#374151", soft="#374151",
        shadow="#111827", chip_bg="#f97316", chip_fg="#1f2937",
        on_accent="#1f2937",
    ),
    # gov: steady navy + restrained red (政企汇报风)
    "gov": dict(
        bg="#f8fafc", ink="#0f172a", body="#334155", muted="#475569",
        accent="#b91c1c", card="#ffffff", border="#e2e8f0", soft="#fee2e2",
        shadow="#e2e8f0", chip_bg="#0f172a", chip_fg="#fca5a5",
    ),
    # med: clean cyan + green (skill: healthcare/medical clean)
    "med": dict(
        bg="#ecfeff", ink="#164e63", body="#0e7490", muted="#155e75",
        accent="#047857", card="#ffffff", border="#a5f3fc", soft="#d1fae5",
        shadow="#a5f3fc", chip_bg="#164e63", chip_fg="#67e8f9",
        on_accent="#ffffff",
    ),
}
for _p in PALETTES.values():
    _p.setdefault("on_accent", "#ffffff")

FONT = (
    '"Microsoft YaHei", "PingFang SC", "Noto Sans CJK SC", '
    '"Source Han Sans SC", Arial, sans-serif'
)

SECTION_CSS = """/* cards.{ind} — GENERATED by tools/build_themes.py, do not edit. */
html, body { width: {{WIDTH}}px; height: {{HEIGHT}}px; margin: 0; overflow: hidden; }
* { box-sizing: border-box; }
body { font-family: FONTSTACK; background: {{BG}}; }
.band { position: absolute; left: 0; top: 0; width: {{WIDTH}}px; height: 10px; background: {{ACCENT}}; }
.num { position: absolute; left: 90px; top: 60px; width: fit-content; background: {{CHIP_BG}}; padding: 4px 14px; border-radius: 8px; }
.num p { margin: 0; color: {{CHIP_FG}}; font-size: 17px; font-weight: 700; letter-spacing: 3px; }
.head { position: absolute; left: 90px; top: 96px; width: {{CONTENT_WIDTH}}px; }
h2 { margin: 0; color: {{INK}}; font-size: 38px; font-weight: 800; line-height: 1.25; }
.rule { position: absolute; left: 90px; top: 172px; width: 96px; height: 4px; background: {{ACCENT}}; border-radius: 2px; }
.content { position: absolute; left: 90px; top: 214px; width: {{CONTENT_WIDTH}}px; }
.card { position: relative; background: {{CARD}}; border: 1px solid {{BORDER}}; border-radius: 14px; padding: 16px 16px 16px 110px; margin: 0 0 14px 0; box-shadow: 6px 6px 0 {{SHADOW}}; }
.cnum { position: absolute; left: 18px; top: 14px; margin: 0; color: {{CNUM}}; font-size: 26px; font-weight: 800; }
.ctext { margin: 0; color: {{BODY}}; font-size: 24px; line-height: 1.5; }
p { margin: 0 0 16px 0; color: {{BODY}}; font-size: 24px; line-height: 1.5; }
.subhead { margin: 0 0 12px 0; color: {{INK}}; font-size: 27px; font-weight: 700; line-height: 1.5; }
.lead { margin: 0 0 16px 0; color: {{CNUM}}; font-size: 24px; line-height: 1.5; font-weight: 700; }
.figcaption { margin: 6px 0 16px 0; color: {{MUTED}}; font-size: 16px; line-height: 1.4; font-weight: 400; }
"""

COVER_CSS = """/* cards.{ind} cover — GENERATED by tools/build_themes.py, do not edit. */
html, body { width: {{WIDTH}}px; height: {{HEIGHT}}px; margin: 0; overflow: hidden; }
* { box-sizing: border-box; }
body { font-family: FONTSTACK; background: {{BG}}; }
.band { position: absolute; left: 0; top: 0; width: {{WIDTH}}px; height: 12px; background: {{ACCENT}}; }
.deco { position: absolute; right: 90px; bottom: 80px; width: 150px; height: 150px; border-radius: 24px; background: {{SOFT}}; }
.deco2 { position: absolute; right: 200px; bottom: 170px; width: 70px; height: 70px; border-radius: 16px; background: {{ACCENT}}; }
.wrap { position: absolute; left: 110px; top: 220px; width: {{WRAP_WIDTH}}px; }
.kicker { margin: 0 0 20px 0; color: {{ACCENT}}; font-size: 20px; font-weight: 700; letter-spacing: 4px; }
h1 { margin: 0 0 28px 0; color: {{INK}}; font-size: 62px; line-height: 1.15; font-weight: 800; }
.sub { margin: 0; color: {{MUTED}}; font-size: 24px; line-height: 1.5; width: {{SUB_WIDTH}}px; }
"""

SITE_SECTION_CSS = """/* site.{ind} — GENERATED by tools/build_themes.py, do not edit. */
html, body { width: {{WIDTH}}px; height: {{HEIGHT}}px; margin: 0; overflow: hidden; }
* { box-sizing: border-box; }
body { font-family: FONTSTACK; background: {{BG}}; }
.nav { position: absolute; left: 0; top: 0; width: {{WIDTH}}px; height: 72px; background: {{CARD}}; border-bottom: 2px solid {{BORDER}}; }
.logo { position: absolute; left: 40px; top: 16px; width: 40px; height: 40px; border-radius: 10px; background: {{ACCENT}}; }
.brand { position: absolute; left: 92px; top: 26px; margin: 0; color: {{INK}}; font-size: 20px; font-weight: 800; letter-spacing: 2px; }
.nitem { position: absolute; top: 18px; height: 36px; padding: 0 16px; border-radius: 999px; }
.nitem p { margin: 0; color: {{MUTED}}; font-size: 15px; line-height: 36px; font-weight: 600; }
.nitem.cur { background: {{ACCENT}}; }
.nitem.cur p { color: {{ON_ACCENT}}; }
.head { position: absolute; left: 90px; top: 92px; width: {{CONTENT_WIDTH}}px; }
h2 { margin: 0; color: {{INK}}; font-size: 34px; font-weight: 800; line-height: 1.25; }
.rule { position: absolute; left: 90px; top: 144px; width: 96px; height: 4px; background: {{ACCENT}}; border-radius: 2px; }
.content { position: absolute; left: 90px; top: 184px; width: {{CONTENT_WIDTH}}px; }
li { margin: 0 0 18px 0; color: {{BODY}}; font-size: 24px; line-height: 1.5; }
p { margin: 0 0 16px 0; color: {{BODY}}; font-size: 24px; line-height: 1.5; }
.subhead { margin: 0 0 12px 0; color: {{INK}}; font-size: 26px; font-weight: 700; line-height: 1.5; }
.lead { margin: 0 0 16px 0; color: {{CNUM}}; font-size: 24px; line-height: 1.5; font-weight: 700; }
.figcaption { margin: 6px 0 16px 0; color: {{MUTED}}; font-size: 16px; line-height: 1.4; font-weight: 400; }
"""

SITE_COVER_CSS = """/* site.{ind} cover — GENERATED by tools/build_themes.py, do not edit. */
html, body { width: {{WIDTH}}px; height: {{HEIGHT}}px; margin: 0; overflow: hidden; }
* { box-sizing: border-box; }
body { font-family: FONTSTACK; background: {{BG}}; }
.nav { position: absolute; left: 0; top: 0; width: {{WIDTH}}px; height: 72px; background: {{CARD}}; border-bottom: 2px solid {{BORDER}}; }
.logo { position: absolute; left: 40px; top: 16px; width: 40px; height: 40px; border-radius: 10px; background: {{ACCENT}}; }
.brand { position: absolute; left: 92px; top: 26px; margin: 0; color: {{INK}}; font-size: 20px; font-weight: 800; letter-spacing: 2px; }
.nitem { position: absolute; top: 18px; height: 36px; padding: 0 16px; border-radius: 999px; }
.nitem p { margin: 0; color: {{MUTED}}; font-size: 15px; line-height: 36px; font-weight: 600; }
.nitem.cur { background: {{ACCENT}}; }
.nitem.cur p { color: {{ON_ACCENT}}; }
.heroBar { position: absolute; left: 0; bottom: 0; width: {{WIDTH}}px; height: 12px; background: {{ACCENT}}; }
.heroPanel { position: absolute; right: 90px; bottom: 60px; width: 340px; height: 190px; border-radius: 28px; background: {{SOFT}}; }
.heroDot { position: absolute; right: 410px; bottom: 236px; width: 64px; height: 64px; border-radius: 16px; background: {{ACCENT}}; }
.wrap { position: absolute; left: 110px; top: 180px; width: {{WRAP_WIDTH}}px; }
.kicker { margin: 0 0 20px 0; color: {{ACCENT}}; font-size: 20px; font-weight: 700; letter-spacing: 4px; }
h1 { margin: 0 0 28px 0; color: {{INK}}; font-size: 62px; line-height: 1.15; font-weight: 800; }
.sub { margin: 0; color: {{MUTED}}; font-size: 24px; line-height: 1.5; width: {{SUB_WIDTH}}px; }
.cover-figs { position: absolute; left: 110px; top: 450px; width: {{WRAP_WIDTH}}px; }
.figcaption { margin: 6px 0 10px 0; color: {{MUTED}}; font-size: 16px; line-height: 1.4; }
"""


def _lum(color: str) -> float:
    r, g, b = (int(color[i : i + 2], 16) / 255.0 for i in (1, 3, 5))

    def f(c: float) -> float:
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def _ratio(fg: str, bg: str) -> float:
    a, b = _lum(fg), _lum(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def audit(tokens: dict[str, str], ind: str) -> None:
    pairs = [
        ("body/bg", tokens["body"], tokens["bg"]),
        ("ink/bg", tokens["ink"], tokens["bg"]),
        ("muted/bg", tokens["muted"], tokens["bg"]),
        ("chip_fg/chip_bg", tokens["chip_fg"], tokens["chip_bg"]),
        ("cnum/card", tokens["CNUM"], tokens["card"]),
        ("ctext/card", tokens["body"], tokens["card"]),
        ("kicker/bg (cover)", tokens["accent"], tokens["bg"]),
        ("sub/bg (cover)", tokens["muted"], tokens["bg"]),
        ("on_accent/accent (nav cur)", tokens["on_accent"], tokens["accent"]),
    ]
    worst = 99.0
    for label, fg, bg in pairs:
        r = _ratio(fg, bg)
        worst = min(worst, r)
        status = "PASS" if r >= 4.5 else "FAIL"
        print(f"  cards.{ind} {label:20s} {r:5.2f}:1 {status}")
        if r < 4.5:
            raise SystemExit(f"contrast audit failed for cards.{ind}: {label} {r:.2f}:1")
    print(f"  cards.{ind} worst pair {worst:.2f}:1 — OK")


def build(ind: str, tokens: dict[str, str]) -> None:
    # The card numeral / lead color must read on the card surface: prefer the
    # accent, fall back to ink/body — deterministic, audit-enforced.
    for candidate in (tokens["accent"], tokens["ink"], tokens["body"]):
        if _ratio(candidate, tokens["card"]) >= 4.5:
            tokens["CNUM"] = candidate
            break
    else:
        raise SystemExit(f"no cnum candidate passes on card for {ind}")
    styles = {
        "cards": (("section.css", SECTION_CSS), ("cover.css", COVER_CSS)),
        "site": (("section.css", SITE_SECTION_CSS), ("cover.css", SITE_COVER_CSS)),
    }
    for style, files in styles.items():
        out = TEMPLATES / f"{style}.{ind}"
        out.mkdir(parents=True, exist_ok=True)
        for name, template in files:
            css = template.replace("FONTSTACK", FONT).replace("{ind}", ind)
            for key, value in tokens.items():
                css = css.replace("{{" + key.upper() + "}}", value)
            (out / name).write_text(css, encoding="utf-8")
    print(f"  wrote cards.{ind} + site.{ind}")


def main() -> None:
    for ind, tokens in PALETTES.items():
        build(ind, tokens)
        audit(tokens, ind)
    print("all generated themes pass the WCAG AA audit")


if __name__ == "__main__":
    main()
